export const GET_DANH_SACH_PHIM = "GET_DANH_SACH_PHIM"
export const GET_PHIM_DANG_CHIEU = "GET_PHIM_DANG_CHIEU"
export const GET_PHIM_SAP_CHIEU = "GET_PHIM_SAP_CHIEU"
export const LAY_THONG_TIN_CHI_TIET_PHIM = "LAY_THONG_TIN_CHI_TIET_PHIM"
export const LAY_THONG_TIN_EDIT_PHIM = 'LAY_THONG_TIN_EDIT_PHIM'