export const DANG_NHAP = "DANG_NHAP"
export const LAY_THONG_TIN_NGUOI_DUNG = "LAY_THONG_TIN_NGUOI_DUNG"
export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG'
export const TIM_KIEM_NGUOI_DUNG = 'TIM_KIEM_NGUOI_DUNG'